<?php return array(
  array(
    'key' => 'footer_settings',
    'label' => 'Footer settings',
    'name' => '',
    'type' => 'tab',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'placement' => 'top',
    'endpoint' => 0,
  ),
  array(
    'key' => 'footer_logo',
    'label' => 'Footer logo',
    'name' => 'footer_logo',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'url',
    'preview_size' => 'thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array(
    'key' => 'footer_text',
    'label' => 'Footer text',
    'name' => 'footer_text',
    'type' => 'wysiwyg',
    'instructions' => 'Text under the logo',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
    'readonly' => 0,
    'disabled' => 0,
  ),
  array(
    'key' => 'footer_mainform',
    'label' => 'Footer main form',
    'name' => 'footer_mainform',
    'type' => 'gravity_forms_field',
    'instructions' => 'The form displayed in the footer of every page',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
  array(
    'key' => 'footer_form',
    'label' => 'Footer form',
    'name' => 'footer_form',
    'type' => 'gravity_forms_field',
    'instructions' => 'The form displayed in the footer of every page',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  )
);
