<?php return array (
  array (
    'key' => 'footer_infobar',
    'label' => 'Footer Infobar',
    'name' => 'footer_infobar',
    'type' => 'tab',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'placement' => 'top',
    'endpoint' => 0,
  ),
  array (
    'key' => 'footer_infobar_image',
    'label' => 'Background image',
    'name' => 'footer_infobar_image',
    'type' => 'image',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'return_format' => 'array',
    'preview_size' => 'thumbnail',
    'library' => 'all',
    'min_width' => '',
    'min_height' => '',
    'min_size' => '',
    'max_width' => '',
    'max_height' => '',
    'max_size' => '',
    'mime_types' => '',
  ),
  array (
    'key' => 'footer_infobar_title',
    'label' => 'Title',
    'name' => 'footer_infobar_title',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
    'readonly' => 0,
    'disabled' => 0,
  ),
  array (
    'key' => 'footer_infobar_text',
    'label' => 'Intro text',
    'name' => 'footer_infobar_text',
    'type' => 'text',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'prepend' => '',
    'append' => '',
    'maxlength' => '',
    'readonly' => 0,
    'disabled' => 0,
  ),
  array (
    'key' => 'footer_infobar_form',
    'label' => 'Form',
    'name' => 'footer_infobar_form',
    'type' => 'gravity_forms_field',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array (
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'allow_null' => 1,
    'allow_multiple' => 0,
  ),
);
