<?php return array (
  'key' => 'page_page_header',
  'title' => 'Page Header',
  'fields' => array (
    array (
      'key' => 'page_header_title',
      'label' => 'Title',
      'name' => 'page_header_title',
      'type' => 'text',
      'instructions' => 'Optional. If left empty, shows the actual page title.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'page_header_content',
      'label' => 'Content',
      'name' => 'page_header_content',
      'type' => 'wysiwyg',
      'instructions' => 'Optional.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'page_template',
        'operator' => '!=',
        'value' => 'template-front.php',
      ),
    ),
  ),
  'menu_order' => 1,
  'position' => 'acf_after_title',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
);
