<?php return array(
  array(
    'key' => 'package_popular',
    'label' => 'Most popular',
    'name' => 'package_popular',
    'type' => 'checkbox',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'choices' => array(
      'popular' => 'Most popular',
    ),
    'allow_custom' => 0,
    'default_value' => array(),
    'layout' => 'vertical',
    'toggle' => 0,
    'return_format' => 'value',
    'save_custom' => 0,
  ),
  array(
    'key' => 'package_subtitle',
    'label' => 'Subtitle text',
    'name' => 'package_subtitle',
    'type' => 'textarea',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
      'width' => '',
      'class' => '',
      'id' => '',
    ),
    'default_value' => '',
    'placeholder' => '',
    'maxlength' => '',
    'rows' => '',
    'new_lines' => '',
  ),
);
